# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Blog posts use the same directory as the existing protected items.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /fb766f3526a3cf4578dd8df5fb6e9b6e96d98635/blog/:title
      protected: true
      sitemap: false

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:               'Abhishek Nath'
description:         'personal website'
author:              'Abhishek Nath'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xmn:
